services:

  fhir-bomber:
    image: ghcr.io/diz-unimr/fhir-bomber:1.2.2
    ports:
      - "8081:8081"
    environment:
      BOMBER_LOG_LEVEL: info
      BOMBER_WORKERS: 15
      BOMBER_INTERVAL: 10m
      FHIR_BASE: http://fhir-base/fhir/
